### ISSUE TITLE
Cannot run or verify database read task.

### ISSUE THREAD

**Issue by larkvincer** [php-school/discussions#3]
I get this error message when trying to verify database task: 
PHP Fatal error:  Uncaught RuntimeException: Database directory: "/tmp/PhpSchool_PhpWorkshop_Check_DatabaseCheck" already exists in /home/larkvincer/.composer/vendor/php-school/php-workshop/src/Check/DatabaseCheck.php:76

**Comment by AydinHassan** [comment]
Hi @larkvincer could you show the version you are using and which OS? Also could you try manually remove that directory and try again?

**Comment by larkvincer** [comment]
I'm using Ubuntu 16.04.1 LTS. When i delete directory it throws another error:
"PHP Fatal error:  Uncaught PDOException: could not find driver in /home/larkvincer/.composer/vendor/php-school/php-workshop/src/Check/DatabaseCheck.php:85"
I tried run again and got the same error like before.

**Comment by AydinHassan** [comment]
Ah this looks like because you are missing the pdo sqlite driver, it should not have installed without it, but I think we added that in a later version, could you maybe try composer global update?

Sent from my iPhone

On 14 Aug 2016, at 16:17, larkvincer <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm using Ubuntu 16.04.1 LTS. When i delete directory it throws another error:
"PHP Fatal error: Uncaught PDOException: could not find driver in /home/larkvincer/.composer/vendor/php-school/php-workshop/src/Check/DatabaseCheck.php:85"
I tried run again and got the same error like before.

##

**Comment by larkvincer** [comment]
I fixed that. Firstly I manually delete /tmp/PhpSchool_PhpWorkshop_Check_DatabaseCheck directory and than install php-sqlite3 with "sudo apt install php-sqlite3". It work's) Thank you)

**Comment by AydinHassan** [comment]
Great! Glad you got it working ?

Sent from my iPhone

On 14 Aug 2016, at 17:27, larkvincer <notifications@github.com<mailto:notifications@github.com>> wrote:

I fixed that. Firstly I manually delete /tmp/PhpSchool_PhpWorkshop_Check_DatabaseCheck directory and than install php-sqlite3 with "sudo apt install php-sqlite3". It work's) Thank you)

##

**Comment by AydinHassan** [comment]
Closing this as it seems to be resolved. Feel free to re-open or create a new issue!
